BEGIN TRANSACTION;
CREATE TABLE "TB_METAQUERY" (
	`id`	INTEGER NOT NULL UNIQUE,
	`metaquery`	TEXT NOT NULL UNIQUE,
	`lang`	TEXT NOT NULL,
	`subject`	TEXT NOT NULL,
	`predicate`	TEXT NOT NULL,
	`object`	TEXT NOT NULL,
	PRIMARY KEY(`id`)
);
CREATE TABLE "TB_CLAIM_TRIPLE" (
	`id`	INTEGER NOT NULL UNIQUE,
	`subject`	TEXT NOT NULL,
	`predicate`	TEXT NOT NULL,
	`object`	TEXT NOT NULL,
	`id_claim`	INTEGER DEFAULT 0,
	PRIMARY KEY(`id`),
	FOREIGN KEY(`id_claim`) REFERENCES tb_claim_text(id)
);
CREATE TABLE `TB_CLAIM_TEXT` (
	`id`	INTEGER NOT NULL UNIQUE,
	`claim`	TEXT NOT NULL UNIQUE,
	`source`	TEXT,
	PRIMARY KEY(`id`)
);
COMMIT;
